---
title: "15 Minute City"
format:
  revealjs:
    css: styles2.css
    center: false
    self-contained: true
execute:
  echo: false
  warning: false
  error: false
  r: true
bibliography: references.bib
---

## Team Members

Randy\
Phillip\
Adil\
Phil\
Lauren

------------------------------------------------------------------------

## Problem Definition

-   What amenities can I reach within 15 minutes?

-   How does that change if I walk, bike, or take the bus?

-   What grocery stores, libraries, or parks can I reach?

------------------------------------------------------------------------

## Objectives

-   Explore the city of Münster.

-   Optimize a 15 minute trip.

-   Reach desired amenities, via specific travel mode.

------------------------------------------------------------------------

## Target Audience

Anyone who benefits from 15 minute excursions, specific to their situation:

-   New residents: selecting a livable neighborhood

-   Current residents: optimize amenity choices

-   Tourists: quick trips around the hotel

------------------------------------------------------------------------

## Description (Initial Idea)

1.  Application opens to a map view.

2.  User clicks location on map and chooses travel mode.

3.  Isochrone appears around selected location.

4.  Side menu pop-up with destination categories.

5.  User selects categories, pins appear in isochrone.

6.  User selects pin and a detailed travel route appears on map.

------------------------------------------------------------------------

## Related Work

Space-time prisms anchored to place-based origin\
Accessibility defined by temporal and spatial constraints\
<span style="font-size: 0.3em;">@Delafontaine2011</span>
<iframe src="Literature/delafontaine_selected.pdf" width="100%" height="550px"></iframe>

------------------------------------------------------------------------

## Related Work

Accessibility mapped by isochrones\
Isochrone area: set of all points reachable ≤ time limit\
<span style="font-size: 0.3em;">@OSullivan2000</span>
<iframe src="Literature/osullivan.pdf" width="100%" height="550px"></iframe>

------------------------------------------------------------------------

## Related Work

Isochrones as tools for planning, design, & communication\
Visually clear and appealing isochrones\
<span style="font-size: 0.3em;">@Dovey2017</span>
<iframe src="Literature/dovey_selected.pdf" width="100%" height="550px"></iframe>

------------------------------------------------------------------------

## Related Work

Schematized travel-time maps\
Reducing visual complexity of isochrones\
<span style="font-size: 0.3em;">@Forsch2021</span>
<iframe src="Literature/forsch_selected.pdf" width="100%" height="550px"></iframe>

------------------------------------------------------------------------

## Related Work

From desktop GIS tools to web application\
Lightweight, user-friendly\
<span style="font-size: 0.3em;">@Gortana2014</span>
<iframe src="Literature/2014-isoscope.pdf" width="100%" height="550px"></iframe>

------------------------------------------------------------------------

## Related Work - Conclusions

-   Existing desktop tools are more complex for beginners

-   We will provide a user friendly, lightweight web application

    +---------------------------------------+--------------------------------------------------------------------------------------------+
    | Challenges                            | Potential Solutions                                                                        |
    +=======================================+============================================================================================+
    | -   clear & accurate isochrones       | -   OSM                                                                                    |
    |                                       |                                                                                            |
    | -   multi-modal functionality         | -   POI API                                                                                |
    |                                       |                                                                                            |
    | -   Resource intensity (computations) | -   [R^5^py](https://r5py.readthedocs.io/stable/) python interface for R^5^ routing engine |
    +---------------------------------------+--------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

## Data

-   Map: OSM Leaflet

-   POIs: OverPass API

-   Routing: R^5^py

------------------------------------------------------------------------

## Visualization (Time & Space)

-   Time: 15 minute travel time

-   Space: isochrones visualizing 15 minute travel zone

------------------------------------------------------------------------

## Progress & Project Management

```{r}
df <- read.delim("Backlog.tsv", header = TRUE, sep = "\t")
df$URL <- NULL
df$Priority <- NULL
df$Estimate <- NULL
df$Size <- NULL
knitr::kable(df, caption = "Project Backlog", align = "l")
```

------------------------------------------------------------------------

## Demonstration

-   Share interface prototype

------------------------------------------------------------------------

## Plans (Before Next Sprint)

-   Evaluation

-   UI improvements

------------------------------------------------------------------------

## References

::: {#refs}
:::